# Generated by Django 3.1.7 on 2021-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20, null=None)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20, null=None)),
                ('Address', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=20)),
            ],
        ),
    ]
